Client/Models/Reservation/EditReservationModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Client.Models
{
	public class EditReservationModel
	{
		public string ReservationId { get; set; }
		[Required(ErrorMessage = "Este campo es obligatorio.")]
		[Display(Name = "Viaje")]
		public string TravelId { get; set; }
		[Required(ErrorMessage = "Este campo es obligatorio.")]
		[Display(Name = "Pasajero")]
		public string TravelerId { get; set; }
	}
}

Client/Models/Reservation/NewReservationModel.cs
using System.ComponentModel.DataAnnotations;

namespace Client.Models
{
	public class NewReservationModel
	{
		[Required(ErrorMessage = "Este campo es obligatorio.")]
		[Display(Name = "Viaje")]
		public string TravelId { get; set; }
		[Required(ErrorMessage = "Este campo es obligatorio.")]
		[Display(Name = "Pasajero")]
		public string TravelerId { get; set; }
	}
}

Client/Models/Reservation/ReservationModel.cs
using System.ComponentModel.DataAnnotations;

namespace Client.Models
{
	public class ReservationModel
	{
		public string Id { get; set; }
		[Required(ErrorMessage = "Este campo es obligatorio.")]
		[Display(Name = "Pasajero")]
		public string TravelerId { get; set; }
		[Required(ErrorMessage = "Este campo es obligatorio.")]
		[Display(Name = "Viaje")]
		public string TravelId { get; set; }
	}
}

Client/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using Client.DTOs;
using Client.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Serilog;

namespace Client.Controllers
{
	public class ReservationController : Controller
	{
		public readonly ILogger Logger;
		private readonly IMapper Mapper;

		public readonly IConfiguration Configure;

		public readonly string ApiBaseUrl;

		public ReservationController(ILogger logger, IMapper mapper, IConfiguration configuration)
		{
			Logger = logger;
			Mapper = mapper;
			Configure = configuration;

			ApiBaseUrl = Configure.GetValue<string>("WebAPIBaseUrl");
		}

		// GET: Travel/Create
		[HttpGet]
		public async Task<IActionResult> Create()
		{
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Travel";
				NewReservationModel model = new NewReservationModel();

				using (var response = await client.GetAsync(endpoint))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string apiResponse = await response.Content.ReadAsStringAsync();

					IEnumerable<TravelDTO> travels = JsonConvert.DeserializeObject<List<TravelDTO>>(apiResponse);

					ViewBag.ListTravels = new SelectList(travels, "Id", "Route");
				}

				string endpointTraveler = $@"{ApiBaseUrl}/Traveler";

				using (var response = await client.GetAsync(endpointTraveler))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string apiResponse = await response.Content.ReadAsStringAsync();

					IEnumerable<TravelerDTO> travelers = JsonConvert.DeserializeObject<List<TravelerDTO>>(apiResponse);

					ViewBag.ListTravelers = new SelectList(travelers, "Id", "Name");
				}

				return View(model);
			}
		}

		// GET: /Reservation/Traveler/{travelerId}
		[HttpGet("/Reservation/Traveler/{travelerId}")]
		public async Task<ActionResult> GetReservationByTraveler(string travelerId)
		{
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Traveler/{travelerId}/Reservation";

				using (var response = await client.GetAsync(endpoint))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string apiResponse = await response.Content.ReadAsStringAsync();

					List<JObject> dataObject = JsonConvert.DeserializeObject<List<JObject>>(apiResponse);
					List<ReservationListDTO> reservations = Mapper.Map<List<ReservationListDTO>>(dataObject);

					return View(reservations);
				}
			}
		}

		// GET: /Reservation/Travel/{travelId}
		[HttpGet("/Reservation/Travel/{travelId}")]
		public async Task<ActionResult> GetReservationByTravel(string travelId)
		{
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Travel/{travelId}/Reservation";

				using (var response = await client.GetAsync(endpoint))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string apiResponse = await response.Content.ReadAsStringAsync();

					List<JObject> dataObject = JsonConvert.DeserializeObject<List<JObject>>(apiResponse);
					List<ReservationListDTO> reservations = Mapper.Map<List<ReservationListDTO>>(dataObject);

					return View(reservations);
				}
			}
		}

		// POST: /Traveler/{travelerId}/Reservation
		[Produces("application/json")]
		[HttpPost]
		public async Task<ActionResult> Create(Guid travelerId, [Bind("TravelId", "TravelerId")] NewReservationModel reservation)
		{
			if (!ModelState.IsValid)
			{
				return BadRequest(reservation);
			}
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Reservation";

				var jsonContent = new StringContent(JsonConvert.SerializeObject(reservation), Encoding.UTF8, "application/json");

				using (var response = await client.PostAsync(endpoint, jsonContent))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string apiResponse = await response.Content.ReadAsStringAsync();

					List<ReservationDTO> reservations = JsonConvert.DeserializeObject<List<ReservationDTO>>(apiResponse);

					return Ok();
				}
			}
		}

		// GET: Reservation/Edit/5
		[HttpGet("/Reservation/Edit/{id}")]
		public async Task<IActionResult> Edit(Guid id)
		{
			if (id == null)
			{
				return BadRequest();
			}
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Reservation/{id}";
				EditReservationModel model = new EditReservationModel();

				using (var response = await client.GetAsync(endpoint))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string apiResponse = await response.Content.ReadAsStringAsync();

					ReservationDTO reservation = JsonConvert.DeserializeObject<ReservationDTO>(apiResponse);

					model.ReservationId = id.ToString();
					model.TravelerId = reservation.TravelerId;
					model.TravelId = reservation.TravelId;
				}
				string endpointTravel = $@"{ApiBaseUrl}/Travel";

				using (var response = await client.GetAsync(endpointTravel))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string apiResponse = await response.Content.ReadAsStringAsync();

					IEnumerable<TravelDTO> travels = JsonConvert.DeserializeObject<List<TravelDTO>>(apiResponse);

					ViewBag.ListTravels = new SelectList(travels, "Id", "Route");
				}

				string endpointTraveler = $@"{ApiBaseUrl}/Traveler";

				using (var response = await client.GetAsync(endpointTraveler))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string apiResponse = await response.Content.ReadAsStringAsync();

					IEnumerable<TravelerDTO> travelers = JsonConvert.DeserializeObject<List<TravelerDTO>>(apiResponse);

					ViewBag.ListTravelers = new SelectList(travelers, "Id", "Name");
				}

				return View(model);
			}
		}

		// Put: Reservation/Edit/5
		[Produces("application/json")]
		[HttpPut("/Reservation/Edit/{id}")]
		public async Task<IActionResult> Edit(Guid id, [Bind("Id,TravelId,TravelerId")] ReservationModel updateReservation)
		{
			if (id.ToString() != updateReservation.Id)
			{
				return BadRequest(updateReservation);
			}
			if (!ModelState.IsValid)
			{
				return BadRequest(updateReservation);
			}
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Reservation/{updateReservation.Id}";

				StringContent jsonContent = new StringContent(JsonConvert.SerializeObject(updateReservation), Encoding.UTF8, "application/json");

				using (var response = await client.PutAsync(endpoint, jsonContent))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}
					return Ok();
				}
			}
		}

		// GET: Travel/Edit/5
		[HttpGet("/Reservation/{id}")]
		public async Task<IActionResult> Details(Guid id)
		{
			if (id == null)
			{
				return BadRequest();
			}
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Reservation/{id}";

				using (var response = await client.GetAsync(endpoint))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string apiResponse = await response.Content.ReadAsStringAsync();

					ReservationDTO reservation = JsonConvert.DeserializeObject<ReservationDTO>(apiResponse);

					return View(reservation);
				}
			}
		}

		// Delete: Travel/Delete/5
		[Produces("application/json")]
		[HttpDelete("/Reservation/Delete/{id}")]
		public async Task<IActionResult> DeleteConfirmed(Guid id)
		{
			if (id == null)
			{
				return BadRequest();
			}
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Reservation/{id}";

				using (var response = await client.DeleteAsync(endpoint))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string endpointGetTravel = $@"{ApiBaseUrl}/Travel";

					using (var responseGetTravel = await client.GetAsync(endpointGetTravel))
					{
						if (!response.IsSuccessStatusCode)
						{
							return StatusCode((int)response.StatusCode);
						}

						string apiResponseGetTravel = await responseGetTravel.Content.ReadAsStringAsync();

						List<JObject> dataObject = JsonConvert.DeserializeObject<List<JObject>>(apiResponseGetTravel);
						List<TravelDTO> reservations = Mapper.Map<List<TravelDTO>>(dataObject);

						return PartialView("_ReservationListPartial", reservations);
					}
				}
			}
		}
	}
}

Client/Views/Reservation/Create.cshtml
@model Client.Models.NewReservationModel

@{
	ViewData["Title"] = "Crear Reservasión";
}

<h2>Reservación</h2>

<h4>Nuevo</h4>
<hr />
<div class="row justify-content-center">
	<div class="col-md-4">
		<form id="CreateReservationForm" asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>

			<div class="form-group">
				<label asp-for="TravelId" class="control-label"></label>
				<!--<input asp-for="TravelId" class="form-control" />-->
				@Html.DropDownListFor(c => c.TravelId, (IEnumerable<SelectListItem>)ViewBag.ListTravels, "Seleccione Viaje", new { @class = "form-control" })
				<span asp-validation-for="TravelId" class="text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="TravelerId" class="control-lable"></label>
				<!--<input asp-for="TravelerId" class="form-control" />-->
				@Html.DropDownListFor(c => c.TravelerId, (IEnumerable<SelectListItem>)ViewBag.ListTravelers, "Seleccione Pasajero", new { @class = "form-control" })
				<span asp-validation-for="TravelerId" class="text-danger"></span>
			</div>

			<div class="row justify-content-center">
				<div class="col-md-9">
					<div id="ErrorAlert" class="alert alert-danger" style="display:none" role="alert">
						Error en los datos enviados!
					</div>
					<div id="SuccessAlert" class="alert alert-success" style="display:none" role="alert">
						Datos guardados correctamente!
					</div>
				</div>
			</div>

			<div class="row justify-content-center">

				<div class="col-md-6">
					<div class="form-group float-right">
						<img id="AjaxLoader" alt="Enviando ..." style="display:none" src="~/img/loading.gif" />
						&nbsp;&nbsp;
						<button id="SubmitBtn" type="submit" class="btn btn-primary">
							Crear
						</button>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>

<div>
	<a class="btn btn-default a-btn-slide-text" asp-action="Index">
		<i class="fas fa-arrow-left" aria-hidden="true"></i>
		<span><strong>Volver a Viajes</strong></span>
	</a>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

	<script type="text/javascript">
		$('#TravelId').change(function () {
			var textValue = $('#TravelId option:selected').text();
			$('#Travel').val(textValue);
		});
		$('#TravelerId').change(function () {
			var textValue = $('#TravelerId option:selected').text();
			$('#Traveler').val(textValue);
		});

		$(function () {
			$("#CreateReservationForm").submit(function (e) {
				e.preventDefault();

				// We show the Ajax Loader
				$("#AjaxLoader").show("fast");

				// We disable the Submit button
				$("#SubmitBtn").prop("disabled", true);

				$.ajax({
					url: "@Url.Action("Create", "Reservation")", // Url
					data: {
						// Data / Parameters
						TravelId: $("#TravelId").val(),
						TravelerId: $("#TravelerId").val()
					},
					type: "post"  // HTTP method
				})
				// Execute if everything went well.
				.done(function (result) {
					if (result != null) {

						// We hide the Ajax Loader
						$("#AjaxLoader").hide("slow");

						// We enable the Submit button
						$("#SubmitBtn").prop("disabled", false);

						// We show a success message.
						$("#SuccessAlert").show("slow").delay(3000).hide("slow");
					}
				})
				// Execute if an error occurred.
				.fail(function (xhr, status, error) {
					// We show an error message.
					$("#ErrorAlert").show("slow").delay(3000).hide("slow");

					// We hide the Ajax Loader
					$("#AjaxLoader").hide("slow");

					// We enable the Submit button
					$("#SubmitBtn").prop("disabled", false);
				})
				// Always execute, whether it was successful or not.
				.always(function () {
					
				});
			});
		});
	</script>
}

Client/Views/Reservation/Details.cshtml
@model Client.DTOs.ReservationListDTO

@{
	ViewData["Title"] = "Detalles";
}

<h2>Reservación</h2>

<div>
	<h4>Detalles</h4>
	<hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.Travel.Origin)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Travel.Origin)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.Travel.Destination)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Travel.Destination)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.Traveler.Name)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Traveler.Name)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.Traveler.Address)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Traveler.Address)
		</dd>
	</dl>
</div>
<div>
	<a class="btn btn-primary a-btn-slide-text" asp-action="Edit" asp-route-id="@Model.Id">
		<i class="fas fa-edit" aria-hidden="true"></i>
		<span><strong>Editar</strong></span>
	</a>
	<a class="btn btn-default a-btn-slide-text" asp-action="Index">
		<i class="fas fa-arrow-left" aria-hidden="true"></i>
		<span><strong>Volver a Viajes</strong></span>
	</a>
</div>

Client/Views/Reservation/Edit.cshtml
@model Client.Models.EditReservationModel

@{
	ViewData["Title"] = "Editar Reservasión";
}


<h2>Reservación</h2>

<h4>Editar</h4>
<hr />
<div class="row justify-content-center">
	<div class="col-md-4">
		<form id="EditReservationForm" asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>

			<input id="ReservationId" type="hidden" asp-for="ReservationId" />

			<div class="form-group">
				<label asp-for="TravelId" class="control-label"></label>
				<!--<input asp-for="TravelId" class="form-control" />-->
				@Html.DropDownListFor(c => c.TravelId, (IEnumerable<SelectListItem>)ViewBag.ListTravels, "Seleccione Viaje", new { @class = "form-control" })
				<span asp-validation-for="TravelId" class="text-danger"></span>

			</div>

			<div class="form-group">
				<label asp-for="TravelerId" class="control-lable"></label>
				<!--<input asp-for="TravelerId" class="form-control" />-->
				@Html.DropDownListFor(c => c.TravelerId, (IEnumerable<SelectListItem>)ViewBag.ListTravelers, "Seleccione Pasajero", new { @class = "form-control" })
				<span asp-validation-for="TravelerId" class="text-danger"></span>

			</div>

			<div class="row justify-content-center">
				<div class="col-md-9">
					<div id="ErrorAlert" class="alert alert-danger" style="display:none" role="alert">
						Error en los datos enviados!
					</div>
					<div id="SuccessAlert" class="alert alert-success" style="display:none" role="alert">
						Datos guardados correctamente!
					</div>
				</div>
			</div>

			<div class="row justify-content-center">

				<div class="col-md-6">
					<div class="form-group float-right">
						<img id="AjaxLoader" alt="Enviando ..." style="display:none" src="~/img/loading.gif" />
						&nbsp;&nbsp;
						<button id="SubmitBtn" type="submit" class="btn btn-primary">
							Guardar
						</button>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>

<div>
	<a class="btn btn-default a-btn-slide-text" asp-action="Index">
		<i class="fas fa-arrow-left" aria-hidden="true"></i>
		<span><strong>Volver a Viajes</strong></span>
	</a>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

	<script type="text/javascript">
		$('#TravelId').change(function () {
			var textValue = $('#TravelId option:selected').text();
			$('#Travel').val(textValue);
		});
		$('#TravelerId').change(function () {
			var textValue = $('#TravelerId option:selected').text();
			$('#Traveler').val(textValue);
		});

		$(function () {
			$("#EditReservationForm").submit(function (e) {
				e.preventDefault();

				// We show the Ajax Loader
				$("#AjaxLoader").show("fast");

				// We disable the Submit button
				$("#SubmitBtn").prop("disabled", true);
				reservationId = $("#ReservationId").val();

				$.ajax({
					url: "@Url.Action("Edit", "Reservation")", // Url
					data: {
						// Data / Parameters
						ReservationId: reservationId,
						TravelId: $("#TravelId").val(),
						TravelerId: $("#TravelerId").val()
					},
					type: "put"  // HTTP method
				})
				// Execute if everything went well.
				.done(function (result) {
					if (result != null) {

						// We hide the Ajax Loader
						$("#AjaxLoader").hide("slow");

						// We enable the Submit button
						$("#SubmitBtn").prop("disabled", false);

						// We show a success message.
						$("#SuccessAlert").show("slow").delay(3000).hide("slow");
					}
				})
				// Execute if an error occurred.
				.fail(function (xhr, status, error) {
					// We show an error message.
					$("#ErrorAlert").show("slow").delay(3000).hide("slow");

					// We hide the Ajax Loader
					$("#AjaxLoader").hide("slow");

					// We enable the Submit button
					$("#SubmitBtn").prop("disabled", false);
				})
				// Always execute, whether it was successful or not.
				.always(function () {
					
				});
			});
		});
	</script>
}

Client/Views/Reservation/GetReservationByTravel.cshtml
@model IEnumerable<Client.DTOs.ReservationListDTO>

@{
	ViewData["Title"] = "Inicio";
}

<h2>Lista de Reservaciones</h2>

<p>
	<a class="btn btn-primary a-btn-slide-text" asp-action="Create">
		<i class="fa fa-plus" aria-hidden="true"></i>
		<span><strong>Agregar</strong></span>
	</a>
</p>


<div class="container">
	<div class="row">
		<div class="col-md-9">
			<div id="ErrorAlert" class="alert alert-danger" style="display:none" role="alert">
				Error al eliminar Reservación!
			</div>
			<div id="SuccessAlert" class="alert alert-success" style="display:none" role="alert">
				Se ha eliminado Satisfactoriamente el registro!
			</div>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col">
			<div id="ReservationList">
				<partial name="_ReservationListPartial" model="Model" />
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="deleteReservationModal" tabindex="-1" role="deleteReservationModal" aria-hidden="true" style="display: none;">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
				<h4 class="modal-title">Confirmación de eliminación de Reservación</h4>
			</div>
			<div class="modal-body">
				¿Estás seguro de querer eliminar este reservación?
			</div>
			<div class="modal-footer">
				<button id="btnContinueDeleteReservation" type="button" class="btn btn-primary">Eliminar</button>
				<button data-dismiss="modal" type="button" class="btn btn-secondary">Cancelar</button>
			</div>
		</div>
	</div>
</div>


@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

	<script type="text/javascript">
		var path_to_delete;

		// Bind the event click to elements with class deleteReservationItem
		$(".deleteReservationItem").click(function(e) {
			// Get path url to call ajax
			path_to_delete = $(this).data('path');
		});

		$('#btnContinueDeleteReservation').click(function (e) {
			e.preventDefault();

			// Mostramos el Ajax Loader
			$("#AjaxLoader").show("fast");

			$.ajax({
				url: path_to_delete, // Url
				data: null, //no send data
				type: "delete"  // HTTP method
			})
			// It Executes if all went well
			.done(function (result) {
				if (result != null) {

					// Update the HTML result
					$("#ReservationList").html(result);

					// A little special effect;)
					$("#ReservationList .row").first().hide();
					$("#ReservationList .row").first().slideToggle("fast");

					// We hide the Ajax Loader
					$("#AjaxLoader").hide("slow");

					// We show a success message.
					$("#SuccessAlert").show("slow").delay(3000).hide("slow");
				}
			})
			// Executes if an error occurred.
			.fail(function (xhr, status, error) {
				// We show an error message.
				$("#ErrorAlert").show("slow").delay(3000).hide("slow");

				// We hide the Ajax Loader
				$("#AjaxLoader").hide("slow");
			})
			// Always execute, successful or not.
			.always(function () {
				$('#deleteReservationModal').modal('hide');
			});
		});
	</script>

} 

Client/Views/Reservation/GetReservationByTraveler.cshtml
@model IEnumerable<Client.DTOs.ReservationListDTO>

@{
	ViewData["Title"] = "Inicio";
}

<h2>Lista de Reservaciones</h2>

<p>
	<a class="btn btn-primary a-btn-slide-text" asp-action="Create">
		<i class="fa fa-plus" aria-hidden="true"></i>
		<span><strong>Agregar</strong></span>
	</a>
</p>


<div class="container">
	<div class="row">
		<div class="col-md-9">
			<div id="ErrorAlert" class="alert alert-danger" style="display:none" role="alert">
				Error al eliminar Reservación!
			</div>
			<div id="SuccessAlert" class="alert alert-success" style="display:none" role="alert">
				Se ha eliminado Satisfactoriamente el registro!
			</div>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col">
			<div id="ReservationList">
				<partial name="_ReservationListPartial" model="Model" />
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="deleteReservationModal" tabindex="-1" role="deleteReservationModal" aria-hidden="true" style="display: none;">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
				<h4 class="modal-title">Confirmación de eliminación de Reservación</h4>
			</div>
			<div class="modal-body">
				¿Estás seguro de querer eliminar esta Reservación?
			</div>
			<div class="modal-footer">
				<button id="btnContinueDeleteReservation" type="button" class="btn btn-primary">Eliminar</button>
				<button data-dismiss="modal" type="button" class="btn btn-secondary">Cancelar</button>
			</div>
		</div>
	</div>
</div>


@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

	<script type="text/javascript">
		var path_to_delete;

		// Bind the event click to elements with class deleteReservationItem
		$(".deleteReservationItem").click(function(e) {
			// Get path url to call ajax
			path_to_delete = $(this).data('path');
		});

		$('#btnContinueDeleteReservation').click(function (e) {
			e.preventDefault();

			// Mostramos el Ajax Loader
			$("#AjaxLoader").show("fast");

			$.ajax({
				url: path_to_delete, // Url
				data: null, //no send data
				type: "delete"  // HTTP method
			})
			// It Executes if all went well
			.done(function (result) {
				if (result != null) {

					// Update the HTML result
					$("#ReservationList").html(result);

					// A little special effect;)
					$("#ReservationList .row").first().hide();
					$("#ReservationList .row").first().slideToggle("fast");

					// We hide the Ajax Loader
					$("#AjaxLoader").hide("slow");

					// We show a success message.
					$("#SuccessAlert").show("slow").delay(3000).hide("slow");
				}
			})
			// Executes if an error occurred.
			.fail(function (xhr, status, error) {
				// We show an error message.
				$("#ErrorAlert").show("slow").delay(3000).hide("slow");

				// We hide the Ajax Loader
				$("#AjaxLoader").hide("slow");
			})
			// Always execute, successful or not.
			.always(function () {
				$('#deleteReservationModal').modal('hide');
			});
		});
	</script>

} 

Client/Views/Reservation/_ReservationListPartial.cshtml
@using Client.DTOs
@model IEnumerable<ReservationListDTO>


@if (Model != null)
{
<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Traveler.Name)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Traveler.DocumentId)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Travel.Origin)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Travel.Destination)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody class=".table-hover">
		@Html.Hidden("item-to-delete", "", new {@id = "item-to-delete"})
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Traveler.Name)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Traveler.DocumentId)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Travel.Origin)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Travel.Destination)
				</td>
				<td>
					<a class="btn btn-primary a-btn-slide-text btn-icon" asp-action="Edit" asp-route-id="@item.Id">
						<i class="fa fa-edit" aria-hidden="true"></i>
					</a>
					<a class="btn btn-info a-btn-slide-text btn-icon" asp-action="Details" asp-route-id="@item.Id">
						<i class="fa fa-eye" aria-hidden="true"></i>
					</a>
					<a class="btn btn-danger a-btn-slide-text btn-icon deleteReservationItem" id="deleteReservationBtn" data-target="#deleteReservationModal" data-toggle="modal" data-id="@item.Id" data-path="@Url.Action("Delete", "Reservation", new { id = @item.Id })">
						<i class="fa fa-trash" aria-hidden="true"></i>
					</a>
				</td>
			</tr>
		}
	</tbody>
</table>
}