Client/Controllers/TravelController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using Client.DTOs;
using Client.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Serilog;

namespace Client.Controllers
{
	public class TravelController : Controller
	{
		public readonly ILogger Logger;
		private readonly IMapper Mapper;

		public readonly IConfiguration Configure;

		public readonly string ApiBaseUrl;

		public TravelController(ILogger logger, IMapper mapper, IConfiguration configuration)
		{
			Logger = logger;
			Mapper = mapper;
			Configure = configuration;

			ApiBaseUrl = Configure.GetValue<string>("WebAPIBaseUrl");
		}

		// GET: Travel
		[HttpGet]
		public async Task<ActionResult> Index()
		{
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Travel";

				using (var response = await client.GetAsync(endpoint))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string apiResponse = await response.Content.ReadAsStringAsync();
					
					List<JObject> dataObject = JsonConvert.DeserializeObject<List<JObject>>(apiResponse);
					List<TravelDTO> travels = Mapper.Map<List<TravelDTO>>(dataObject);

					return View(travels);
				}
			}
		}

		// GET: Travel/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: Travel/Create
		[Produces("application/json")]
		[HttpPost]
		public async Task<IActionResult> Create([Bind("Origin,Destination,Seats,Price")] NewTravelModel travel)
		{
			if (!ModelState.IsValid)
			{
				return BadRequest(travel);
			}
			List<TravelDTO> travels = null;
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Travel";

				var jsonContent = new StringContent(JsonConvert.SerializeObject(travel), Encoding.UTF8, "application/json");

				using (var response = await client.PostAsync(endpoint, jsonContent))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string apiResponse = await response.Content.ReadAsStringAsync();

					travels = JsonConvert.DeserializeObject<List<TravelDTO>>(apiResponse);

					return Ok();
				}
			}
		}

		// GET: Travel/Edit/5
		[HttpGet, Route("/Travel/Edit/{id}")]
		public async Task<IActionResult> Edit(Guid id)
		{
			if (id == null)
			{
				return BadRequest();
			}
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Travel/{id}";

				using (var response = await client.GetAsync(endpoint))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string apiResponse = await response.Content.ReadAsStringAsync();

					TravelDTO travel = JsonConvert.DeserializeObject<TravelDTO>(apiResponse);

					return View(travel);
				}
			}
		}

		// Put: Travel/Edit/5
		[Produces("application/json")]
		[HttpPut, Route("/Travel/Edit/{id}")]
		public async Task<IActionResult> Edit(Guid id, [Bind("Id,Origin,Destination,Seats,Price")] TravelModel travel)
		{
			if (id.ToString() != travel.Id)
			{
				return BadRequest(travel);
			}
			if (!ModelState.IsValid)
			{
				return BadRequest(travel);
			}
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Travel/{travel.Id}";

				StringContent jsonContent = new StringContent(JsonConvert.SerializeObject(travel), Encoding.UTF8, "application/json");

				using (var response = await client.PutAsync(endpoint, jsonContent))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string endpointGetTravel = $@"{ApiBaseUrl}/Travel";

					using (var responseGetTravel = await client.GetAsync(endpointGetTravel))
					{
						if (!response.IsSuccessStatusCode)
						{
							return StatusCode((int)response.StatusCode);
						}

						string apiResponseGetTravel = await responseGetTravel.Content.ReadAsStringAsync();

						List<JObject> dataObject = JsonConvert.DeserializeObject<List<JObject>>(apiResponseGetTravel);
						List<TravelDTO> travels = Mapper.Map<List<TravelDTO>>(dataObject);

						return PartialView("_TravelListPartial", travels);
					}
				}
			}
		}

		// GET: Travel/Edit/5
		[HttpGet, Route("/Travel/Details/{id}")]
		public async Task<IActionResult> Details(Guid id)
		{
			if (id == null)
			{
				return BadRequest();
			}
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Travel/{id}";

				using (var response = await client.GetAsync(endpoint))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string apiResponse = await response.Content.ReadAsStringAsync();

					TravelDTO travel = JsonConvert.DeserializeObject<TravelDTO>(apiResponse);

					return View(travel);
				}
			}
		}

		// Delete: Travel/Delete/5
		[Produces("application/json")]
		[HttpDelete, Route("/Travel/delete/{id}")]
		public async Task<IActionResult> DeleteConfirmed(Guid id)
		{
			if (id == null)
			{
				return BadRequest();
			}
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Travel/{id}";

				using (var response = await client.DeleteAsync(endpoint))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string endpointGetTravel = $@"{ApiBaseUrl}/Travel";

					using (var responseGetTravel = await client.GetAsync(endpointGetTravel))
					{
						if (!response.IsSuccessStatusCode)
						{
							return StatusCode((int)response.StatusCode);
						}

						string apiResponseGetTravel = await responseGetTravel.Content.ReadAsStringAsync();

						List<JObject> dataObject = JsonConvert.DeserializeObject<List<JObject>>(apiResponseGetTravel);
						List<TravelDTO> travels = Mapper.Map<List<TravelDTO>>(dataObject);

						return PartialView("_TravelListPartial", travels);
					}
				}
			}
		}
	}
}

Client/Controllers/TravelerController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using Client.DTOs;
using Client.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Serilog;

namespace Client.Controllers
{
	public class TravelerController : Controller
	{
		public readonly ILogger Logger;
		private readonly IMapper Mapper;

		public readonly IConfiguration Configure;

		public readonly string ApiBaseUrl;

		public TravelerController(ILogger logger, IMapper mapper, IConfiguration configuration)
		{
			Logger = logger;
			Mapper = mapper;
			Configure = configuration;

			ApiBaseUrl = Configure.GetValue<string>("WebAPIBaseUrl");
		}

		// GET: Traveler
		[HttpGet]
		public async Task<ActionResult> Index()
		{
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Traveler";

				using (var response = await client.GetAsync(endpoint))
				{
					if (response.IsSuccessStatusCode)
					{
						string apiResponse = await response.Content.ReadAsStringAsync();

						List<JObject> dataObject = JsonConvert.DeserializeObject<List<JObject>>(apiResponse);
						List<TravelerDTO> travelers = Mapper.Map<List<TravelerDTO>>(dataObject);

						return View(travelers);
					}
					return StatusCode((int)response.StatusCode);
				}
			}
		}

		// GET: Traveler/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: Traveler/Create
		[Produces("application/json")]
		[HttpPost]
		public async Task<IActionResult> Create([Bind("Name,DocumentId,Address,Phone")] NewTravelerModel traveler)
		{
			if (!ModelState.IsValid)
			{
				return BadRequest(traveler);
			}
			List<TravelerDTO> travelers = null;
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Traveler";

				var jsonContent = new StringContent(JsonConvert.SerializeObject(traveler), Encoding.UTF8, "application/json");

				using (var response = await client.PostAsync(endpoint, jsonContent))
				{
					if (response.IsSuccessStatusCode)
					{
						string apiResponse = await response.Content.ReadAsStringAsync();

						travelers = JsonConvert.DeserializeObject<List<TravelerDTO>>(apiResponse);

						return Ok();
					}
					return StatusCode((int)response.StatusCode);
				}
			}
		}

		// GET: Traveler/Edit/5
		[HttpGet, Route("/Traveler/Edit/{id}")]
		public async Task<IActionResult> Edit(Guid id)
		{
			if (id == null)
			{
				return BadRequest();
			}
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Traveler/{id}";

				using (var response = await client.GetAsync(endpoint))
				{
					if (response.IsSuccessStatusCode)
					{
						string apiResponse = await response.Content.ReadAsStringAsync();

						TravelerDTO traveler = JsonConvert.DeserializeObject<TravelerDTO>(apiResponse);

						return View(traveler);
					}
					return StatusCode((int)response.StatusCode);
				}
			}
		}

		// Put: Traveler/Edit/5
		[Produces("application/json")]
		[HttpPut, Route("/Traveler/Edit/{id}")]
		public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,DocumentId,Address,Phone")] TravelerModel traveler)
		{
			if (id.ToString() != traveler.Id)
			{
				return BadRequest(traveler);
			}
			if (!ModelState.IsValid)
			{
				return BadRequest(traveler);
			}
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Traveler/{traveler.Id}";

				StringContent jsonContent = new StringContent(JsonConvert.SerializeObject(traveler), Encoding.UTF8, "application/json");

				using (var response = await client.PutAsync(endpoint, jsonContent))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}
					string endpointGetTraveler = $@"{ApiBaseUrl}/Traveler";

					using (var responseGetTraveler = await client.GetAsync(endpointGetTraveler))
					{
						if (!response.IsSuccessStatusCode)
						{
							return StatusCode((int)response.StatusCode);
						}
						string apiResponseGetTraveler = await responseGetTraveler.Content.ReadAsStringAsync();

						List<JObject> dataObject = JsonConvert.DeserializeObject<List<JObject>>(apiResponseGetTraveler);
						List<TravelerDTO> travelers = Mapper.Map<List<TravelerDTO>>(dataObject);

						return PartialView("_TravelerListPartial", travelers);
					}
				}
			}
		}

		// GET: Traveler/Edit/5
		[HttpGet, Route("/Traveler/Details/{id}")]
		public async Task<IActionResult> Details(Guid id)
		{
			if (id == null)
			{
				return BadRequest();
			}
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Traveler/{id}";

				using (var response = await client.GetAsync(endpoint))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string apiResponse = await response.Content.ReadAsStringAsync();

					TravelerDTO traveler = JsonConvert.DeserializeObject<TravelerDTO>(apiResponse);

					return View(traveler);
				}
			}
		}

		// Delete: Traveler/Delete/5
		[Produces("application/json")]
		[HttpDelete, Route("/Traveler/Delete/{id}")]
		public async Task<IActionResult> DeleteConfirmed(Guid id)
		{
			if (id == null)
			{
				return BadRequest();
			}
			using (HttpClient client = new HttpClient())
			{
				string endpoint = $@"{ApiBaseUrl}/Traveler/{id}";

				using (var response = await client.DeleteAsync(endpoint))
				{
					if (!response.IsSuccessStatusCode)
					{
						return StatusCode((int)response.StatusCode);
					}

					string endpointGetTraveler = $@"{ApiBaseUrl}/Traveler";

					using (var responseGetTraveler = await client.GetAsync(endpointGetTraveler))
					{
						if (!response.IsSuccessStatusCode)
						{
							return StatusCode((int)response.StatusCode);
						}

						string apiResponseGetTraveler = await responseGetTraveler.Content.ReadAsStringAsync();

						List<JObject> dataObject = JsonConvert.DeserializeObject<List<JObject>>(apiResponseGetTraveler);
						List<TravelerDTO> travelers = Mapper.Map<List<TravelerDTO>>(dataObject);

						return PartialView("_TravelerListPartial", travelers);
					}
				}
			}
		}
	}
}

Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome.5.15.1/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Client</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Travel" asp-action="Index">Viajes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Traveler" asp-action="Index">Viajeros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Client/Views/Shared/_ModalHeader.cshtml
<!--Modal-->
<div class="modal" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Coonfirmar eliminación</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<p>¿Estas seguro de querer eliminar este item?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary">Eliminar</button>
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
			</div>
		</div>
	</div>
</div>

Client/Views/Shared/_ModelBody.cshtml
<!--Modal-->
<div class="modal" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Coonfirmar eliminación</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<p>¿Estas seguro de querer eliminar este item?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary">Eliminar</button>
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
			</div>
		</div>
	</div>
</div>

Client/Views/Shared/_ModelFooter.cshtml
<!--Modal-->
<div class="modal" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Coonfirmar eliminación</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<p>¿Estas seguro de querer eliminar este item?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary">Eliminar</button>
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
			</div>
		</div>
	</div>
</div>